Added composition task
vtrushevsky/PMK22_cryptology pull request #2
Opened 2023-03-04 09:41 UTC by clar1k

2023-03-11 19:26 UTC, vtrushevsky commented on Polymorphism/Khara/Поліморфізм/main.cpp
> +	virtual string getPhoneType() = 0;
getPhoneType() method should be const

2023-03-11 19:27 UTC, vtrushevsky commented on Polymorphism/Khara/Поліморфізм/main.cpp
> +	virtual string printPhone()
printPhone( ) should be const

2023-03-11 19:40 UTC, vtrushevsky commented on Polymorphism/Khara/Поліморфізм/main.cpp
> +	virtual bool getAutoResponse()
getAutoResponse( ) should return false by default, because in this case all mobile phones also with auto response.

2023-03-11 19:47 UTC, vtrushevsky commented on Polymorphism/Khara/Поліморфізм/main.cpp
> +	virtual bool setFiltered()
setFiltered and getFiltered shouldn't be virtual, because behavior is the same in child classes as well, moreover these methods are not needed at all, you can filter out phones by using method  getPhoneType( ) - this method also shouldn't be virtual, field phoneType (enum type) better to have in a class Phone. Then in  a main you can filter out radio phones based on  getPhoneType( ) and getAutoResponse( ).

2023-03-11 19:59 UTC, vtrushevsky commented on Composition/Khara/Talon/main.cpp
> +	int GetScore() { return talon.GetScore(); }
All get methods should be const

2023-03-11 20:01 UTC, vtrushevsky commented on Composition/Khara/Talon/main.cpp
> +	string GetPredmet() { return predmet; }
All get methods should be const

2023-03-11 20:06 UTC, vtrushevsky commented on Composition/Khara/Talon/main.cpp
> +		if (array[i].GetScore() > 0 && array[i].GetScore() < 10)
This task is not implemented  - вивести у Файл1 список студентів, які мають більше одного талону

2023-03-11 20:07 UTC, vtrushevsky commented on Composition/Khara/Talon/main.cpp
> +	for (int i = 0; i < n; i++)
This task is not implemeted - Видрукувати у Файл2 прізвище викладача, який фігурує в найбільшій кількості талонів.

2023-03-11 20:21 UTC, vtrushevsky requested changes
Please keep only *.cpp and *.txt files in your branch on GitHub, all other files should be removed.

2023-03-12 07:55 UTC, clar1k commented on Polymorphism/Khara/Поліморфізм/main.cpp
> +	virtual bool setFiltered()
Can i get higher mark if i fix what did you said?

2023-06-04 20:16 UTC, vtrushevsky commented on Algorithm/Хара Сергій/algorithm.cpp
> +	for (size_t i = 0; i < books.size() - 1; i++)
adjacent_find can be used instead

2023-06-04 20:17 UTC, vtrushevsky commented on Algorithm/Хара Сергій/algorithm.cpp
> +	while (i < books1.size() && j < books2.size())
std:search can be used instead

2023-06-04 20:20 UTC, vtrushevsky commented on Algorithm/Хара Сергій/algorithm.cpp
> +}
This task is done partially - 10б

2023-06-04 20:24 UTC, vtrushevsky commented on MultInheritance/Khara/MultiInheritance.cpp
> +
5б

2023-06-04 20:28 UTC, vtrushevsky commented on RhombInheritance/Khara/Rhomb.cpp
> +	Car** a = new Car * [3];
At the end memory should be deallocated

2023-06-04 20:30 UTC, vtrushevsky commented on RhombInheritance/Khara/Rhomb.cpp
> +}
This point is not implemented: Знайти марку, яка містить авто всіх трьох типів.
4б

2023-06-04 20:40 UTC, vtrushevsky commented on List/Khara/main.cpp
> +//}
This task is done partially, Class Iterator is mіssing for list, also there no move and copy constructors and assignment operators:
продемонструвати роботу конструкторів та операторів для копіювання та переміщення списків, додавши відповідні коментарі в коді програми (де і який конструктор/оператор спрацьовує).

15б

2023-06-04 20:42 UTC, vtrushevsky commented on FormatText/Хара Сергій/format_text.cpp
> +int main()
why main is empty?
4б

2023-06-04 20:44 UTC, vtrushevsky commented on Map/Хара/map.cpp
> +}
10б

2024-03-15 08:02 UTC, closed without merging